### PR TITLE
Fix GitHub Actions

### PR DESCRIPTION
**Pull request by devarops**
Fix GitHub Actions using [ggplot2's config file](https://github.com/tidyverse/ggplot2/blob/master/.github/workflows/R-CMD-check.yaml) as a template.

In addition, use Ubuntu 18.04 (Bionic) instead of 16.04 (Xenial).

### CODE REVIEW

**Comment by devarops** [comment]
New _master_ branch fixes most of the jobs in `R-CMD-check`

**Comment by sckott** [comment]
thanks - was going to get to this after pushing up the many changes I had. if you think the actions file needs changes, i'm open to it. i didn't understand a few of the changes though, such as why have the package sf installation steps as its not used here - and I don't want to remove the test step,  as tests will be added soon

**Comment by devarops** [comment]
Some of these changes don't make sense any longer. You fixed the warnings in the _master_. I had disabled the warnings in this PR just to get the green check. Now that the warnings are fixed, it is better to leave the warnings on.

I'll look into the last job currently failing in R 4.0 (Ubuntu 16.04): `Package required but not available: ‘pkgapi’`. If I can fix it I'll submit a new PR.

**Comment by sckott** [comment]
thanks, i wasn't sure why pkgapi failed to install

**Pull request closed without merging**
